nginx:
  image: nginx:alpine
  links:
    - pea
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  expose:
    - "8080"

pea:
  image: propersoft/docker-cd:pea
  volumes:
    - ./pea-cd-entrypoint.sh:/pea-cd-entrypoint.sh 
  environment:
    - WORKDIR=/opt/pea
    - GH_OAUTH_TOKEN=10d05c4cae61d4c5289d79964472414d29bd630c
  expose:
    - "9000"  
    - "8080"     
  entrypoint: /pea-cd-entrypoint.sh