nginx:
  image: nginx:alpine
  links:
    - pea
  external_links:
    - pea_pep1_official_1
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  expose:
    - "8080"

pea:
  image: propersoft/docker-cd:pea
  volumes:
    - ./pea-cd-entrypoint.sh:/pea-cd-entrypoint.sh 
  environment:
    - WORKDIR=/opt/pea
  expose:
    - "9000"  
    - "8080"     
  entrypoint: chmod +x /pea-cd-entrypoint.sh
  entrypoint: /pea-cd-entrypoint.sh
