nginx:
  image: nginx:alpine
  links:
    - ihos
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  expose:
    - "8080"

ihos:
  image: node:latest
  volumes:
    - ./entrypoint.sh:/entrypoint.sh
  environment:
    - WORKDIR=/opt/ihos
    - GH_OAUTH_TOKEN
  entrypoint: /entrypoint.sh
