nginx:
  image: nginx:alpine
  links:
    - ihos
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  expose:
    - "8080"

ihos:
  image: propersoft/docker-cd:ihos
  environment:
    - GH_OAUTH_TOKEN